In [21]:
# 최종 전략 csv
import pandas as pd
# Yun_final=pd.read_csv('./YunFinal.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yunseo'})
# Yun_proto=pd.read_csv('./YunOriginal.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yunseo_proto'})
# Yong=pd.read_csv('./Young_Final.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yong'})
Moon=pd.read_csv('./Moon_final.csv').iloc[:,[8,6]].rename(columns={'PnL':'Moon'})
Moon_proto=pd.read_csv('./Moon_proto.csv').iloc[:,[8,6]].rename(columns={'PnL':'Moon_proto'})
# Yong=pd.read_csv('./Young_final.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yong'})
# Yong_proto =pd.read_csv('./Young_base.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yong_proto'})
final=pd.merge(Moon, Moon_proto, how='outer',on='EntryTime')
# final=pd.merge(final, Seo, how='outer',on='EntryTime')
# final=pd.merge(final, Moon, how='outer',on='EntryTime')

final=final.fillna(0.0)
final.sort_values(by='EntryTime',inplace=True)

In [23]:
final.to_csv('Moon_add.csv')

In [22]:
final

                EntryTime          Moon   Moon_proto
709   2017-08-18 21:00:00      0.000000 -3378.009724
710   2017-08-21 05:15:00      0.000000 -3205.799432
711   2017-08-21 23:00:00      0.000000   205.897012
712   2017-08-23 08:45:00      0.000000  1070.372252
0     2017-08-23 18:15:00 -13211.833968     0.000000
...                   ...           ...          ...
707   2023-01-13 18:45:00    684.118548     0.000000
1423  2023-01-15 08:45:00      0.000000  1472.401968
1424  2023-01-17 00:15:00      0.000000 -4763.031120
708   2023-01-17 23:15:00   3903.080712     0.000000
1425  2023-01-17 23:30:00      0.000000    54.541560

[1426 rows x 3 columns]

In [2]:
# 프로토타입 전략 csv
import pandas as pd
Yun_final=pd.read_csv('./YunOriginal.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yunseo'})
Yong=pd.read_csv('./Young_base.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yong'})
Moon=pd.read_csv('./Moon_proto.csv').iloc[:,[8,6]].rename(columns={'PnL':'Moon'})
Seo=pd.read_csv('./Lee_base.csv').iloc[:,[8,6]].rename(columns={'PnL':'Seoho'})
proto_final=pd.merge(Yong, Yun_final, how='outer',on='EntryTime')
proto_final=pd.merge(proto_final, Seo, how='outer',on='EntryTime')
proto_final=pd.merge(proto_final, Moon, how='outer',on='EntryTime')

proto_final=proto_final.fillna(0.0)
proto_final.sort_values(by='EntryTime',inplace=True)

In [5]:
proto_final.to_csv('proto_final.csv')

In [2]:
import pandas as pd
# Yun_final=pd.read_csv('./YunFinal.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yunseo'})
# Yong=pd.read_csv('./Young_Final.csv').iloc[:,[8,6]].rename(columns={'PnL':'Yong'})
# Moon=pd.read_csv('./Moon_final.csv').iloc[:,[8,6]].rename(columns={'PnL':'Moon'})
Seo=pd.read_csv('./Lee_final.csv').iloc[:,[8,6]].rename(columns={'PnL':'Seoho'})
proto_Seo =pd.read_csv('./Lee_base.csv').iloc[:,[8,6]].rename(columns={'PnL':'proto_Seoho'})
# final=pd.merge(Yong, Yun_final, how='outer',on='EntryTime')
seo_final=pd.merge(final, Seo, how='outer',on='EntryTime')
# final=pd.merge(final, Moon, how='outer',on='EntryTime')

seo_final=seo_final.fillna(0.0)
seo_final.sort_values(by='EntryTime',inplace=True)

NameError: name 'final' is not defined

In [24]:
final

,EntryTime,Yong,Yunseo,Seoho_x,Moon,Seoho_y
0,2017-08-19 18:30:00,-42317.621872,0.0,0.00000,0.000000,0.00000
1,2017-08-23 18:15:00,0.000000,0.0,-330.94836,-13211.833968,-330.94836
2,2017-08-23 19:15:00,0.000000,0.0,-4511.31984,0.000000,-4511.31984
3,2017-08-23 21:45:00,55255.492515,0.0,0.00000,0.000000,0.00000
4,2017-08-25 08:15:00,0.000000,0.0,-3901.72284,0.000000,-3901.72284
...,...,...,...,...,...,...
4671,2023-01-05 23:30:00,0.000000,0.0,0.00000,-70095.067896,0.00000
4672,2023-01-09 19:15:00,0.000000,0.0,0.00000,-3722.578020,0.00000
4673,2023-01-10 17:45:00,0.000000,0.0,0.00000,163177.142616,0.00000
4674,2023-01-13 18:45:00,0.000000,0.0,0.00000,684.118548,0.00000
4675,2023-01-17 23:15:00,0.000000,0.0,0.00000,3903.080712,0.00000